services:
  app:
    build:
      context: .
      target: development
    container_name: bluewave_dataroom
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
      - .env.local
    working_dir: /usr/src/app
